### ISSUE TITLE
support for variable substitution

### ISSUE THREAD

**Issue by surajssd** [redhat-developer/henge#13]
When used variables that are available in environment variables list, henge does not substitute the varaibles properly but fails.
Using compose following compose file:

```bash
$ cat docker-compose.yml 
version: "2"

services:
  mariadb:
    image: centos/mariadb
    ports:
      - "$DB_PORT"
    environment:
      MYSQL_ROOT_PASSWORD: $ROOT_PASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_USER: $DB_USER

  etherpad:
    image: centos/etherpad
    ports:
      - "80:9001"
    depends_on:
      - mariadb
    environment:
      DB_HOST: $DB_HOST
      DB_DBID: $DB_NAME
      DB_PASS: $DB_PASS
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
```
environment file
```bash
$ cat envs 
DB_HOST=mariadb
ROOT_PASS=etherpad
DB_NAME=etherpad
DB_PASS=etherpad
DB_USER=etherpad
DB_PORT=3306
```

build and run
```bash
$ export $(cat envs)
$ go build ../../../henge.go 
$ ./henge docker-compose.yml 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x618bf4]

goroutine 1 [running]:
panic(0x10cc900, 0xc820010130)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/redhat-developer/henge/vendor/github.com/openshift/origin/third_party/github.com/docker/libcompose/project.interpolate.func1(0xc82032f260, 0x7, 0x0, 0x0)
	/home/vagrant/work/src/github.com/redhat-developer/henge/vendor/github.com/openshift/origin/third_party/github.com/docker/libcompose/project/interpolation.go:155 +0x84
github.com/redhat-developer/henge/vendor/github.com/openshift/origin/third_party/github.com/docker/libcompose/project.parseVariable(0xc82032eba8, 0x8, 0x8, 0xc8200a0150, 0x0, 0x0, 0xc800000000, 0xc8202ef810)
	/home/vagrant/work/src/github.com/redhat-developer/henge/vendor/github.com/openshift/origin/third_party/github.com/docker/libcompose/project/interpolation.go:37 +0x120
github.com/redhat-developer/henge/vendor/github.com/openshift/origin/third_party/github.com/docker/libcompose/project.parseInterpolationExpression(0xc82032eba8, 0x8, 0x1, 0xc8200a0150, 0x0, 0x0, 0xeb0da0, 0x412f18)
	/home/vagrant/work/src/github.com/redhat-developer/henge/vendor/github.com/openshift/origin/third_party/github.com/docker/libcompose/project/interpolation.go:75 +0x10f
github.com/redhat-developer/henge/vendor/github.com/openshift/origin/third_party/github.com/docker/libcompose/project.parseLine(0xc82032eba8, 0x8, 0xc8200a0150, 0x0, 0x0, 0x195)
	/home/vagrant/work/src/github.com/redhat-developer/henge/vendor/github.com/openshift/origin/third_party/github.com/docker/libcompose/project/interpolation.go:91 +0xbf
github.com/redhat-developer/henge/vendor/github.com/openshift/origin/third_party/github.com/docker/libcompose/project.parseConfig(0xc82032eba0, 0x5, 0xc82032eb58, 0x7, 0xc82009fef8, 0xc8200a0150, 0x0, 0x0)
	/home/vagrant/work/src/github.com/redhat-developer/henge/vendor/github.com/openshift/origin/third_party/github.com/docker/libcompose/project/interpolation.go:111 +0x538
github.com/redhat-developer/henge/vendor/github.com/openshift/origin/third_party/github.com/docker/libcompose/project.parseConfig(0xc82032eba0, 0x5, 0xc82032eb58, 0x7, 0xc8200a00d0, 0xc8200a0150, 0x0, 0x0)
	/home/vagrant/work/src/github.com/redhat-developer/henge/vendor/github.com/openshift/origin/third_party/github.com/docker/libcompose/project/interpolation.go:128 +0x1dc
github.com/redhat-developer/henge/vendor/github.com/openshift/origin/third_party/github.com/docker/libcompose/project.interpolate(0x0, 0x0, 0xc8200b82f0, 0x0, 0x0)
	/home/vagrant/work/src/github.com/redhat-developer/henge/vendor/github.com/openshift/origin/third_party/github.com/docker/libcompose/project/interpolation.go:154 +0x1f3
github.com/redhat-developer/henge/vendor/github.com/openshift/origin/third_party/github.com/docker/libcompose/project.mergeProject(0xc82022ad80, 0xc8201d5180, 0x49, 0xc82032a400, 0x1d9, 0x3d9, 0x8, 0x0, 0x0)
	/home/vagrant/work/src/github.com/redhat-developer/henge/vendor/github.com/openshift/origin/third_party/github.com/docker/libcompose/project/merge.go:59 +0x253
github.com/redhat-developer/henge/vendor/github.com/openshift/origin/third_party/github.com/docker/libcompose/project.(*Project).load(0xc82022ad80, 0xc8201d5180, 0x49, 0xc82032a400, 0x1d9, 0x3d9, 0x0, 0x0)
	/home/vagrant/work/src/github.com/redhat-developer/henge/vendor/github.com/openshift/origin/third_party/github.com/docker/libcompose/project/project.go:127 +0x111
github.com/redhat-developer/henge/vendor/github.com/openshift/origin/third_party/github.com/docker/libcompose/project.(*Project).Parse(0xc82022ad80, 0x0, 0x0)
	/home/vagrant/work/src/github.com/redhat-developer/henge/vendor/github.com/openshift/origin/third_party/github.com/docker/libcompose/project/project.go:67 +0x327
github.com/redhat-developer/henge/pkg/generate/dockercompose.Generate(0xc82000a2d0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/vagrant/work/src/github.com/redhat-developer/henge/pkg/generate/dockercompose/generate.go:60 +0x450
main.main()
	/home/vagrant/henge/henge.go:58 +0x21c
```

Go version

```bash
$ go version
go version go1.6.2 linux/amd64
```

**Comment by surajssd** [comment]
Variable substitution works in [libcompose](https://github.com/docker/libcompose) but currently fails in OpenShift so the issue https://github.com/openshift/origin/issues/9058 regarding that is reported.

docker-compose file
```bash
$ cat docker-compose.yml 
version: "2"

services:
  mariadb:
    image: centos/mariadb
    ports:
      - "$DB_PORT"
    environment:
      MYSQL_ROOT_PASSWORD: $ROOT_PASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_USER: $DB_USER
```

envs
```bash
$ cat envs 
ROOT_PASS=etherpad
DB_NAME=etherpad
DB_PASS=etherpad
DB_USER=etherpad
DB_PORT=3306
```

running it using libcompose
```bash
$ export $(cat envs)
$ ./libcompose up
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose) 
INFO[0000] Project [temp]: Starting project             
INFO[0000] [0/1] [mariadb]: Starting                    
INFO[0000] [1/1] [mariadb]: Started                     
INFO[0000] Project [temp]: Project started              
mariadb_1 | Running mysql_install_db ...
mariadb_1 | Installing MariaDB/MySQL system tables in '/var/lib/mysql' ...
mariadb_1 | 160606 14:50:20 [Note] /usr/libexec/mysqld (mysqld 5.5.47-MariaDB) starting as process 32 ...
mariadb_1 | OK
mariadb_1 | Filling help tables...
mariadb_1 | 160606 14:50:21 [Note] /usr/libexec/mysqld (mysqld 5.5.47-MariaDB) starting as process 39 ...
mariadb_1 | OK
[SNIP]
mariadb_1 | http://mariadb.com/kb/en/contributing-to-the-mariadb-project/
mariadb_1 | 
mariadb_1 | Finished mysql_install_db
mariadb_1 | 160606 14:50:21 mysqld_safe Logging to '/var/log/mariadb/mariadb.log'.
mariadb_1 | 160606 14:50:21 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
^C
Gracefully stopping...
ERRO[0038] Failed EventType: 0 mariadb : net/http: request canceled 
ERRO[0038] Failed to start: mariadb : net/http: request canceled 
```

env vars injected (this was run while above was running in second tab)
```bash
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                     NAMES
f2c7beec3fcd        centos/mariadb      "/docker-entrypoint.s"   12 seconds ago      Up 10 seconds       0.0.0.0:32781->3306/tcp   temp_mariadb_1

$ docker exec -it temp_mariadb_1 bash
bash-4.2$ env                                                                                                                                                                                
HOSTNAME=f2c7beec3fcd
MYSQL_DATABASE=etherpad
MYSQL_PASSWORD=etherpad
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
SHLVL=1
HOME=/var/lib/mysql
MYSQL_USER=etherpad
MYSQL_ROOT_PASSWORD=etherpad
_=/usr/bin/env
bash-4.2$ exit
```

**Comment by surajssd** [comment]
A fix for this problem in OpenShift https://github.com/openshift/origin/pull/9316

**Comment by surajssd** [comment]
Closing since https://github.com/redhat-developer/henge/pull/18 is merged
